=== nghianguyentek/docs/language/formative/markup/xml/sample/cs2205.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="exercises">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="date" type="xs:date" />
                <xs:element name="item" type="xs:string" minOccurs="2" maxOccurs="2"/>
            </xs:sequence>
            <xs:attribute name="number" type="xs:nonNegativeInteger" fixed="1" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="first" type="xs:string"/>
                            <xs:element name="last" type="xs:string"/>
                            <xs:element name="middle" type="xs:string" nillable="true"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="occupation" type="xs:string"/>
                <xs:element name="hobbies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hobby" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="semesters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="semester" minOccurs="2" maxOccurs="2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:nonNegativeInteger">
                                        <xs:enumeration value="2008"/>
                                        <xs:enumeration value="2009"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="period">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Spring"/>
                                        <xs:enumeration value="Fall"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="courses">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="course" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="category">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="General"/>
                                                                <xs:enumeration value="Core"/>
                                                                <xs:enumeration value="Major"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="goal" minOccurs="0">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:nonNegativeInteger">
                                                                <xs:enumeration value="8"/>
                                                                <xs:enumeration value="11"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nghianguyentek/docs/language/formative/markup/xml/sample/exercise02.xml
<?xml version="1.0" encoding="UTF-8" ?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kihon.vn/cs2205.xsd">
    <name>
        <first>First</first>
        <last>Last</last>
        <middle>Middle</middle>
    </name>
    <occupation>Software Developer</occupation>
    <hobbies>
        <hobby>Coding</hobby>
        <hobby>Aikido</hobby>
        <hobby>Mobile Game</hobby>
    </hobbies>
</person>

=== nghianguyentek/docs/language/formative/markup/xml/sample/programOfStudy.xml
<?xml version="1.0" encoding="UTF-8" ?>
<semesters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kihon.vn/cs2205.xsd">
    <semester>
        <year>2008</year>
        <period>Fall</period>
        <courses>
            <course>
                <category>General</category>
                <name>PHIL 101</name>
                <goal>8</goal>
            </course>
            <course>
                <category>General</category>
                <name>ECON 201</name>
                <goal>11</goal>
            </course>
            <course>
                <category>Core</category>
                <name>MGT 217</name>
            </course>
            <course>
                <category>Major</category>
                <name>CIS 120</name>
            </course>
            <course>
                <category>Major</category>
                <name>CIS 403</name>
            </course>
        </courses>
    </semester>
    <semester>
        <year>2009</year>
        <period>Spring</period>
        <courses>
            <course>
                <category>Core</category>
                <name>MGT 261</name>
            </course>
            <course>
                <category>Core</category>
                <name>MGT 325</name>
            </course>
            <course>
                <category>Major</category>
                <name>CIS 220</name>
            </course>
            <course>
                <category>Major</category>
                <name>CIS 407</name>
            </course>
            <course>
                <category>Major</category>
                <name>CIS 490</name>
            </course>
        </courses>
    </semester>
</semesters>
